// plugins/agentz/runtime/client-ipart-starters/react-vite/src/App.jsx
import React, { useEffect, useId, useState } from "react";
import { getPartyContext } from "./imis/party-context.js";
import { readInstanceSettings } from "./imis/settings.js";

export function App({ instance }) {
  const headingId = useId();
  const [state, setState] = useState({ status: "loading", message: "Loading" });

  useEffect(() => {
    const controller = new AbortController();
    readInstanceSettings(instance, __SETTINGS_DEFAULTS_JSON__, controller.signal)
      .then((settings) => {
        if (controller.signal.aborted) return;
        const context = getPartyContext();
        instance.dataset.contentItemKey = settings.contentItemKey;
        instance.setAttribute("aria-busy", "false");
        setState({
          status: "ready",
          message: `${__EXPECTED_MARKER_JS__}${settings.heading ? ` ${settings.heading}` : ""}${context.selectedPartyId ? ` for Party ${context.selectedPartyId}` : ""}`,
        });
      })
      .catch((error) => {
        if (controller.signal.aborted) return;
        instance.setAttribute("aria-busy", "false");
        setState({ status: "error", message: error instanceof Error ? error.message : "The iPart could not start." });
      });
    return () => controller.abort();
  }, [instance]);

  return (
    <div aria-labelledby={headingId} data-state={state.status}>
      <h2 id={headingId}>{__PROJECT_NAME_JS__}</h2>
      <p role="status" aria-live="polite">{state.message}</p>
    </div>
  );
}

// plugins/agentz/runtime/client-ipart-starters/angular/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, input, signal } from "@angular/core";
import { getPartyContext } from "../imis/party-context";
import { readInstanceSettings } from "../imis/settings";

@Component({
  selector: "agentz-client-ipart-app",
  standalone: true,
  template: `
    <div [attr.data-state]="state()">
      <h2>{{ projectName }}</h2>
      <p role="status" aria-live="polite">{{ message() }}</p>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly projectName = __PROJECT_NAME_JS__;
  readonly instance = input.required<Element>();
  readonly state = signal("loading");
  readonly message = signal("Loading");

  constructor() {
    queueMicrotask(() => void this.start());
  }

  private async start(): Promise<void> {
    const instance = this.instance();
    try {
      const settings = await readInstanceSettings(instance, __SETTINGS_DEFAULTS_JSON__);
      const context = getPartyContext();
      (instance as HTMLElement).dataset["contentItemKey"] = settings.contentItemKey;
      instance.setAttribute("aria-busy", "false");
      this.state.set("ready");
      this.message.set(`${__EXPECTED_MARKER_JS__}${settings["heading"] ? ` ${String(settings["heading"])}` : ""}${context.selectedPartyId ? ` for Party ${context.selectedPartyId}` : ""}`);
    } catch (error) {
      instance.setAttribute("aria-busy", "false");
      this.state.set("error");
      this.message.set(error instanceof Error ? error.message : "The iPart could not start.");
    }
  }
}
